# Generated by Django 4.1 on 2022-09-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrydate', models.DateTimeField(auto_now_add=True)),
                ('fulltitle', models.TextField()),
                ('pubyear', models.IntegerField()),
                ('consnumber', models.CharField(max_length=20)),
                ('authorship', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('pubformat', models.CharField(max_length=100)),
            ],
        ),
    ]
