# Generated by Django 4.1 on 2022-09-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catstat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogues',
            name='authorship',
            field=models.CharField(choices=[('Single', 'Single'), ('Collaboration', 'Collaboration'), ('Compilation', 'Compilation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='catalogues',
            name='consnumber',
            field=models.CharField(default='461/', max_length=20),
        ),
        migrations.AlterField(
            model_name='catalogues',
            name='entrydate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='catalogues',
            name='genre',
            field=models.CharField(choices=[('General', 'General'), ('Literature', 'Literature'), ('Biography', 'Biography')], max_length=100),
        ),
        migrations.AlterField(
            model_name='catalogues',
            name='language',
            field=models.CharField(choices=[('Indonesian', 'Indonesian'), ('English', 'English'), ('Indonesian local', 'Indonesian local')], max_length=50),
        ),
        migrations.AlterField(
            model_name='catalogues',
            name='pubformat',
            field=models.CharField(choices=[('Book', 'Book'), ('Non book', 'Non book')], max_length=100),
        ),
    ]
