# Generated by Django 4.1 on 2022-09-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catstat', '0002_alter_catalogues_authorship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogues',
            name='entrydate',
            field=models.DateTimeField(),
        ),
    ]
