# Generated by Django 4.1 on 2022-09-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catstat', '0002_city_catalogues_bibliography_catalogues_indexx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogues',
            name='authorship_type',
            field=models.CharField(choices=[('Single work', 'Single work'), ('Collaboration', 'Collaboration'), ('Compilation', 'Compilation'), ('N_A', 'N_A')], default='Single', max_length=50),
        ),
    ]
