# Generated by Django 4.1 on 2022-09-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catstat', '0003_alter_catalogues_entrydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogues',
            name='entrydate',
            field=models.DateField(),
        ),
    ]
