# Generated by Django 4.1 on 2022-09-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catstat', '0004_alter_catalogues_entrydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogues',
            name='worktype',
            field=models.CharField(choices=[('Original', 'Original'), ('Translation', 'Translation'), ('Adaptation', 'Adaptation')], default='Original', max_length=20),
        ),
    ]
