# Generated by Django 4.1 on 2022-09-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catstat', '0005_catalogues_worktype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogues',
            name='publisher',
        ),
        migrations.AddField(
            model_name='catalogues',
            name='publishertype',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Government-department', 'Government-department'), ('Government-nondepartment', 'Government-nondepartment'), ('Government-local', 'Government-local'), ('Universities', 'Universities'), ('NGO', 'NGO'), ('Others', 'Others')], default='Commercial', max_length=100),
        ),
    ]
