# Generated by Django 4.1 on 2022-09-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catstat', '0006_remove_catalogues_publisher_catalogues_publishertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogues',
            name='authorship',
            field=models.CharField(choices=[('Single', 'Single'), ('Collaboration', 'Collaboration'), ('Compilation', 'Compilation')], default='Single', max_length=50),
        ),
        migrations.AlterField(
            model_name='catalogues',
            name='genre',
            field=models.CharField(choices=[('General', 'General'), ('Literature', 'Literature'), ('Biography', 'Biography')], default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='catalogues',
            name='language',
            field=models.CharField(choices=[('Indonesian', 'Indonesian'), ('English', 'English'), ('Indonesian local', 'Indonesian local')], default='Indonesian', max_length=50),
        ),
        migrations.AlterField(
            model_name='catalogues',
            name='pubformat',
            field=models.CharField(choices=[('Book', 'Book'), ('Non book', 'Non book')], default='Book', max_length=100),
        ),
    ]
