# Generated by Django 4.1.1 on 2022-09-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catstat', '0007_alter_catalogues_authorship_alter_catalogues_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booksize', models.CharField(max_length=10)),
            ],
        ),
    ]
